title: The Rending of Palaghast
description: A Daggerheart Campaign Frame
theme: just-the-docs

url: https://whensuddenlygames.github.io/TheRending

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  # Color scheme supports "light" (default) and "dark"
color_scheme: scooby

logo: "imgs/palaghast-logo-small.png"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2025 Mystery Monster Mayhem! by When Suddenly! Games designer Jeffrey N Baker."
