title: The Rending of Palaghast
description: A Daggerheart Campaign Frame
theme: just-the-docs

url: https://whensuddenlygames.github.io/TheRending

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
