title: The Rending of Palaghast
description: A Daggerheart Campaign Frame with a brand new Domain, new community, and ancestry.
theme: just-the-docs

url: https://whensuddenlygames.github.io/TheRending

aux_links:
  Template Repository: https://github.com/whensuddenlygames/TheRending

  # Color scheme supports "light" (default) and "dark"
color_scheme: abyssal

logo: "imgs/palaghast-logo-small.png"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2025 The Rending of Palaghast by When Suddenly! Games designer Jeffrey N Baker. | Darrington Press:tm: and the Darrington Press authorized work logo are 
trademarks of Critical Role, LLC and used with permission."
